"""Add SchoolClass table manually

Revision ID: 03949eb70766
Revises: 0ad093577d06
Create Date: 2025-06-29 13:27:49.406239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03949eb70766'
down_revision: Union[str, None] = '0ad093577d06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'school_classes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('class_code', sa.String(length=50), nullable=False, unique=True),
        sa.Column('grade', sa.String(length=50), nullable=False),
        sa.Column('teacher', sa.String(length=100), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('class_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_classes')
    # ### end Alembic commands ###
