"""Add school_class_id to Task model

Revision ID: d209d70ea919
Revises: 03949eb70766
Create Date: 2025-06-29 15:05:18.394441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd209d70ea919'
down_revision: Union[str, None] = '03949eb70766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_class_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tasks_school_class_id', 'school_classes', ['school_class_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_school_class_id', type_='foreignkey')
        batch_op.drop_column('school_class_id')
    # ### end Alembic commands ###
